"""Builds the M1-20 graybox kit: every item of art/generators/graybox/kit.py → export.py → check.py (budget class
'graybox'), then writes content/assets/graybox.yaml (the manifest). Usage: python3 tools/art/build_kit.py [--previews]
"""
import json, pathlib, re, subprocess, sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
BLENDER = "/Applications/Blender.app/Contents/MacOS/Blender"
GEN = "art/generators/graybox/kit.py"
sys.path.insert(0, str(ROOT / "art" / "generators" / "graybox"))
ITEMS = [l.split('"')[1] for l in (ROOT / GEN).read_text().splitlines() if re.match(r'\s+"[a-z_]+": \("(char|prop|bldg|nature)"', l) for _ in [0]]
ITEMS = sorted(set(re.findall(r'"([a-z_]+)": \("(?:char|prop|bldg|nature)"', (ROOT / GEN).read_text())), key=lambda n: (ROOT / GEN).read_text().index(f'"{n}": ('))
CATS = dict(re.findall(r'"([a-z_]+)": \("(char|prop|bldg|nature)"', (ROOT / GEN).read_text()))
FOLDER = {"char": "characters/graybox", "prop": "props/graybox", "bldg": "buildings/graybox", "nature": "nature/graybox"}


def run(script, *args):
    out = subprocess.run([BLENDER, "-b", "--factory-startup", "-P", script, "--", *args], cwd=ROOT, capture_output=True, text=True)
    line = next((l for l in out.stdout.splitlines() if l.startswith("RESULT ")), None)
    if line is None:
        sys.exit(f"{script} {args}: no RESULT\n{out.stdout[-2000:]}\n{out.stderr[-2000:]}")
    return json.loads(line[7:])


entries, failed = [], 0
for item in ITEMS:
    cat = CATS[item]
    out = f"game/assets/{FOLDER[cat]}/{cat}_{item}_a.glb"
    res = run("tools/art/export.py", GEN, out, json.dumps({"item": item}))
    chk = run("tools/art/check.py", out, "graybox")
    if not chk["ok"]:
        failed += 1
        print(f"FAIL {item}: {chk['problems']}")
    if "--previews" in sys.argv:
        run("tools/art/preview.py", out, f"art/previews/{cat}_{item}_a")
    print(f"{'ok  ' if chk['ok'] else 'FAIL'} {out}  tris {chk['tris']['0']}  height {chk.get('height_m')} m")
    entries.append((item, cat, out, chk["tris"]["0"], len(chk["materials"])))

lines = ["# yaml-language-server: $schema=../schemas/asset.schema.json",
         "# M1-20 graybox kit (32 §2: placeholders are first-class): generated by art/generators/graybox/kit.py via",
         "# tools/art/build_kit.py; budget class 'graybox'. Status review: only the owner approves a look."]
for item, cat, out, tris, mats in entries:
    lines += [f"- id: asset.graybox.{cat}_{item}", "  kind: model", "  status: review", "  milestone: M1", "  source:", "    type: generator",
              f"    generator: {GEN}", f"    params: {{ item: {item} }}", "    tool: Blender 5.1.0 (headless)", f"  outputs: [{out}]",
              "  budget_class: graybox", f"  measured: {{ tris_lod0: {tris}, materials: {mats} }}",
              "  license: { name: Proprietary-own-work, author: FeudalSim, attribution_required: false }"]
(ROOT / "content" / "assets" / "graybox.yaml").write_text("\n".join(lines) + "\n")
print(f"kit: {len(entries)} assets, {failed} failed checks; wrote content/assets/graybox.yaml")
sys.exit(1 if failed else 0)
