#!/usr/bin/env python3
"""M1-21 placeholder audio (32 §16): dialogue UI sounds and vocal "bark" placeholders, synthesized deterministically,
checked (tools/audio/check.py), with manifest entries (content/assets/audio_m1.yaml) and event mappings
(content/audio/dialogue.yaml). Usage: python3 tools/audio/build_m1.py
"""
import json, pathlib, subprocess, sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools" / "audio"))
from synth import BARKS  # noqa: E402

UI = ["open", "close", "confirm", "unsay", "glyph", "error"]
jobs = []   # (recipe, seed, out, asset id, mapping id)
for kind in BARKS:
    for take, voice in ((1, "low"), (2, "high")):
        jobs.append((f"bark_{kind}_{voice}", 10 + take, f"game/assets/audio/vox/vox_bark_{kind}_{take:02d}.wav", f"asset.vox.bark_{kind}_{take:02d}", f"audio.bark.{kind}"))
for name in UI:
    jobs.append((f"ui_{name}", 3, f"game/assets/audio/ui/ui_dialogue_{name}_01.wav", f"asset.ui.dialogue_{name}_01", f"audio.ui.dialogue_{name}"))

manifest = ["# yaml-language-server: $schema=../schemas/asset.schema.json",
            "# M1-21 placeholders (32 §16): synthesized by tools/audio/synth.py via tools/audio/build_m1.py. Real voice sessions from M2."]
failed = 0
for recipe, seed, out, asset, _ in jobs:
    (ROOT / out).parent.mkdir(parents=True, exist_ok=True)
    subprocess.run([sys.executable, "tools/audio/synth.py", recipe, out, str(seed)], cwd=ROOT, check=True, capture_output=True)
    r = json.loads(subprocess.run([sys.executable, "tools/audio/check.py", out], cwd=ROOT, capture_output=True, text=True).stdout.strip().splitlines()[-1][7:])
    f = r["files"][0]
    if not f["ok"]:
        failed += 1
    print(f"{'ok  ' if f['ok'] else 'FAIL'} {out}  {f['duration_s']} s  {f['loudness_lufs']} LUFS  {f['problems'] or ''}")
    kind = "vocal" if out.startswith("game/assets/audio/vox") else "ui"
    manifest += [f"- id: {asset}", f"  kind: {'sfx' if kind == 'ui' else 'vocal'}", "  status: review", "  milestone: M1",
                 f"  source: {{ type: synthesized, generator: tools/audio/synth.py, params: {{ recipe: {recipe}, seed: {seed} }}, tool: numpy }}",
                 f"  outputs: [{out}]", f"  measured: {{ peak_dbfs: {f['peak_dbfs']}, loudness_lufs: {f['loudness_lufs']}, duration_s: {f['duration_s']} }}",
                 "  license: { name: Proprietary-own-work, author: FeudalSim, attribution_required: false }"]
(ROOT / "content" / "assets" / "audio_m1.yaml").write_text("\n".join(manifest) + "\n")

mapping = ["# yaml-language-server: $schema=../schemas/audio.schema.json",
           "# M1-21: dialogue UI sounds and reaction barks (19 §6.9 gestures → vocal placeholders, two voices per bark).",
           "# Generated by tools/audio/build_m1.py."]
by_id = {}
for _, _, out, _, mid in jobs:
    by_id.setdefault(mid, []).append(out)
for mid, files in by_id.items():
    vocal = mid.startswith("audio.bark.")
    mapping += [f"- id: {mid}", f"  bus: {'vocal' if vocal else 'ui'}", f"  files: [{', '.join(files)}]", f"  spatial: {'true' if vocal else 'false'}",
                f"  pitch_jitter: {0.06 if vocal else 0.02}", f"  volume_jitter_db: {2 if vocal else 0}"]
(ROOT / "content" / "audio" / "dialogue.yaml").write_text("\n".join(mapping) + "\n")
print(f"m1 audio: {len(jobs)} files, {failed} failed checks; wrote content/assets/audio_m1.yaml and content/audio/dialogue.yaml")
sys.exit(1 if failed else 0)
